export const COLLISION_BODIES = {
  // Bodies on which we want to add collision callback
  PLAYER: "player",
  HEALTH: "health",
  PATH: "path",
  WALL: "wall",
  SIDEWALL: "sidewall",
  CENTERRAMP: "centerramp",
  ENDRAMP: "endramp",
  SPINNER: "spinner",
  GEM: "gem",
  OBSTACLE: "obstacle",
  SCOREBOX: "scorebox",
};

export const WINBOX_PROPS = [
  //FRONT WALL
  {
    isFrontWall: true,
    positionZ: 2.5,
    positionY: 0,
    color: 0xff0000,
    positionX: -8,
    score: "1X",
    rotationY: 0,
    rotationX: 0,
  },
  {
    isFrontWall: true,
    positionZ: 2.5,
    positionY: 0,
    color: 0xfff44f,
    positionX: -4,
    score: "3X",
    rotationY: 0,
    rotationX: 0,
  },
  {
    isFrontWall: true,
    positionZ: 2.5,
    positionY: 0,
    color: 0x74b72e,
    positionX: 0,
    score: "5X",
    rotationY: 0,
    rotationX: 0,
  },
  {
    isFrontWall: true,
    positionZ: 2.5,
    positionY: 0,
    color: 0xfff44f,
    positionX: 4,
    score: "3X",
    rotationY: 0,
    rotationX: 0,
  },
  {
    isFrontWall: true,
    positionZ: 2.5,
    positionY: 0,
    color: 0xff0000,
    positionX: 8,
    score: "1X",
    rotationY: 0,
    rotationX: 0,
  },
  //BEHIND WALL
  {
    isFrontWall: false,
    positionZ: -1.5,
    positionY: 0,
    color: 0xff0000,
    positionX: -8,
    score: "1X",
    rotationY: 0,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: -1.5,
    positionY: 0,
    color: 0xfff44f,
    positionX: -4,
    score: "3X",
    rotationY: 0,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: -1.5,
    positionY: 0,
    color: 0x74b72e,
    positionX: 0,
    score: "5X",
    rotationY: 0,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: -1.5,
    positionY: 0,
    color: 0xfff44f,
    positionX: 4,
    score: "3X",
    rotationY: 0,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: -1.5,
    positionY: 0,
    color: 0xff0000,
    positionX: 8,
    score: "1X",
    rotationY: 0,
    rotationX: 0,
  },

  //LEFT WALL
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0xff0000,
    positionX: -10,
    score: "1X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0xfff44f,
    positionX: -6,
    score: "3X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0x74b72e,
    positionX: -2,
    score: "5X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0xfff44f,
    positionX: 2,
    score: "3X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0xff0000,
    positionX: 6,
    score: "1X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },

  //RIGHT WALL
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0xff0000,
    positionX: -6,
    score: "1X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0xfff44f,
    positionX: -2,
    score: "3X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0x74b72e,
    positionX: 2,
    score: "5X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0xfff44f,
    positionX: 6,
    score: "3X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: 0,
    color: 0xff0000,
    positionX: 10,
    score: "1X",
    rotationY: Math.PI / 2,
    rotationX: 0,
  },

  //BOTTOM WALL
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: -1.5,
    color: 0xff0000,
    positionX: -8,
    score: "1X",
    rotationY: 0,
    rotationX: Math.PI / 2,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: -1.5,
    color: 0xfff44f,
    positionX: -4,
    score: "3X",
    rotationY: 0,
    rotationX: Math.PI / 2,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: -1.5,
    color: 0x74b72e,
    positionX: 0,
    score: "5X",
    rotationY: 0,
    rotationX: Math.PI / 2,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: -1.5,
    color: 0xfff44f,
    positionX: 4,
    score: "3X",
    rotationY: 0,
    rotationX: Math.PI / 2,
  },
  {
    isFrontWall: false,
    positionZ: 0.5,
    positionY: -1.5,
    color: 0xff0000,
    positionX: 8,
    score: "1X",
    rotationY: 0,
    rotationX: Math.PI / 2,
  },
];

export const SOURCES = [
  {
    name: "ObstacleArmLiverHammer",
    type: "fbxModel",
    path: "models/Obstacle/HammerOneSideAnimation.fbx",
  },
  {
    name: "ObstacleLegLiverHammer",
    type: "fbxModel",
    path: "models/Obstacle/HammerBothSide.fbx",
  },
  {
    name: "ObstacleLiverAxe",
    type: "fbxModel",
    path: "models/Obstacle/KnifeOneSideAnimation.fbx",
  },
  {
    name: "ObstacleBowlingPin",
    type: "fbxModel",
    path: "models/Obstacle/BowlingPin.FBX",
  },
  {
    name: "Ramp1",
    type: "fbxModel",
    path: "models/Ramps/Ramp1.fbx",
  },
  {
    name: "CenterRamp",
    type: "fbxModel",
    path: "models/Ramps/MidRamp.fbx",
  },
  {
    name: "CenterRampTexture",
    type: "texture",
    path: "models/Ramps/rampa 1.png",
  },
  {
    name: "GemBall",
    type: "fbxModel",
    path: "models/BallAndGem/Gem.fbx",
  },
  {
    name: "HealthBall",
    type: "fbxModel",
    path: "models/BallAndGem/Ball.fbx",
  },
  {
    name: "groundTexture",
    type: "texture",
    path: "textures/ground.png",
  },
  {
    name: "SpinnerObstacle",
    type: "fbxModel",
    path: "models/Obstacle/spinnerObs.fbx",
  },
  {
    name: "EndSpinner",
    type: "fbxModel",
    path: "models/Obstacle/SpinnerEnd.fbx",
  },
  {
    name: "scoreFont",
    type: "font",
    path: "fonts/LilitaOne_Regular.json",
  },
  {
    name: "Buildings",
    type: "fbxModel",
    path: "models/Enviornment/St_Building.FBX",
  },
  {
    name: "BuildingsTexture",
    type: "texture",
    path: "models/Enviornment/RGB Alpha.png",
  },
  {
    name: "FinishLine",
    type: "fbxModel",
    path: "models/Ramps/finishline.fbx",
  },
  {
    name: "HudGem",
    type: "texture",
    path: "textures/Gem Blue.png",
  },
  {
    name: "ProgressBarBg",
    type: "texture",
    path: "textures/Progress Bar Background.png",
  },
  {
    name: "ProgressBarFg",
    type: "texture",
    path: "textures/Level Bar Turquoise.png",
  },
  {
    name: "ProgressBarLevel",
    type: "texture",
    path: "textures/Progress Bar Small Turquoise.png",
  },
  {
    name: "PlayerBall",
    type: "texture",
    path: "textures/PlayerBall.png",
  },
  {
    name: "environmentMapTexture",
    type: "cubeTexture",
    path: [
      "textures/environmentMap/px.png",
      "textures/environmentMap/nx.png",
      "textures/environmentMap/py.png",
      "textures/environmentMap/ny.png",
      "textures/environmentMap/pz.png",
      "textures/environmentMap/nz.png",
    ],
  },
];
